apiVersion: apps/v1
kind: Deployment
metadata:
  name: irrigator
  namespace: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: irrigator
  template:
    metadata:
      labels:
        app: irrigator
    spec:
      serviceAccountName: irrigator
      containers:
      - name: irrigator
        image: ghcr.io/hauke-cloud/irrigator:latest
        args:
        - --api-addr=:8443
        - --probe-addr=:8081
        - --metrics-addr=:8080
        - --leader-election=true
        - --valve-controller-url=https://valve-controller.mqtt.svc.cluster.local:8443
        ports:
        - containerPort: 8443
          name: api
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        - containerPort: 8081
          name: probe
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: probe
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: probe
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        volumeMounts:
        - name: server-tls
          mountPath: /tls
        - name: client-ca
          mountPath: /tls-client-ca
        - name: valve-client-tls
          mountPath: /valve-client-tls
        - name: valve-server-ca
          mountPath: /valve-server-ca
      terminationGracePeriodSeconds: 10
      volumes:
      - name: server-tls
        secret:
          secretName: irrigator-tls
      - name: client-ca
        secret:
          secretName: irrigator-client-ca
      - name: valve-client-tls
        secret:
          secretName: irrigator-valve-client-tls
      - name: valve-server-ca
        secret:
          secretName: irrigator-valve-server-ca
