apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: irrigator-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: irrigator-role
subjects:
- kind: ServiceAccount
  name: irrigator
  namespace: iot
