apiVersion: v1
kind: Service
metadata:
  name: {{ include "irrigator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "irrigator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "irrigator.selectorLabels" . | nindent 4 }}
  ports:
  - name: api
    port: {{ .Values.service.port }}
    targetPort: api
    protocol: TCP
  - name: metrics
    port: {{ .Values.ports.metrics }}
    targetPort: metrics
    protocol: TCP
